Update HA-zg.yml

diff --git a/.github/workflows/HA-zg.yml b/.github/workflows/HA-zg.yml
--- a/.github/workflows/HA-zg.yml
+++ b/.github/workflows/HA-zg.yml
@@ -1,4 +1,4 @@
-name: HA-ZG
+name: haos-china1
 on:
   workflow_dispatch:
     inputs:
@@ -9,8 +9,6 @@ on:
 
   schedule:
     - cron: '0 18 26 * *'
-#  watch:
-#    types: [started]
 
 env:
   RUN_VALIDATION: true
@@ -42,52 +40,45 @@ jobs:
     steps:
       - name: Echo target
         run: echo "Building for ${{ matrix.target }}"
-        #target: [generic_aarch64,generic_x86_64]
 
-    #steps:
       - name: Checkout
         uses: actions/checkout@v5
-        
-      - name: Get HAOS-ZG version
+
+      - name: Get haos-china version
         id: get_haos_version
         run: |
           ver=$(curl -s https://api.github.com/repos/home-assistant/operating-system/releases/latest | jq -r '.tag_name')
           echo "HASSOS_VERSION=${ver}" >> $GITHUB_ENV
-        
-      - name: Initialization environment and Free up disk space
+
+      - name: Initialization and Free up disk space
         run: |
           sudo timedatectl set-timezone "Asia/Shanghai"
-          sudo rm -rf /usr/local/lib/android
-          sudo rm -rf /opt/ghc
-          sudo rm -rf /var/lib/apt/lists/*
-          sudo rm -rf /var/cache/apt/archives/*
-          sudo rm -rf /var/cache/debconf/*-old
-          sudo rm -rf /opt/hostedtoolcache/CodeQL
+          sudo rm -rf /usr/local/lib/android /opt/ghc /var/lib/apt/lists/* /var/cache/apt/archives/* /var/cache/debconf/*-old /opt/hostedtoolcache/CodeQL
           sudo apt clean
           sudo rm -rf /etc/apt/sources.list.d/*
           sudo apt-get -qq update -y
           sudo apt-get -qq autoremove --purge -y
           sudo apt-get -qq clean -y
-          sudo rm -rf "/usr/local/share/boost"
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-          #sudo rm -rf /usr/share/
+          sudo rm -rf "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
           df -h
 
-
-      - name: Clone source code and Change Settings.
+      - name: Clone source and configure overlay
         run: |
           git clone https://github.com/home-assistant/operating-system.git -b main
           cp -r buildroot-external operating-system
           cd operating-system
           git submodule update --init
-          echo "replace key information"
-          sed -i 's|version.home-assistant.io|gitee.com/wuwzn/version/raw/master|g' buildroot-external/package/hassio/hassio.mk
+
+          echo "Replace key information"
+          sed -i 's|version.home-assistant.io|version.hasscn.top|g' buildroot-external/package/hassio/hassio.mk
           sed -i 's|ghcr.io/home-assistant|ghcr.nju.edu.cn/ha-china|g' buildroot-external/package/hassio/dind-import-containers.sh
           sed -i 's|ghcr.io/home-assistant|ghcr.nju.edu.cn/ha-china|g' buildroot-external/rootfs-overlay/usr/sbin/hassos-supervisor
-          sed -i 's|checkonline.home-assistant.io|gitee.com/wuwzn/version/raw/master|g' buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf
+          sed -i 's|checkonline.home-assistant.io|version.hasscn.top|g' buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf
           sed -i 's|time.cloudflare.com|cn.ntp.org.cn|g' buildroot-external/rootfs-overlay/etc/systemd/timesyncd.conf
-          sed -i 's|green}_defconfig)|green,panther_x2,ihost,orangepi_cm4}_defconfig)|' scripts/update-kernel-upstream.sh
+          sed -i 's|green}_defconfig)|green,panther_x2,ihost}_defconfig)|' scripts/update-kernel-upstream.sh
           sed -i '/^set -e$/a export FORCE_UNSAFE_CONFIGURE=1' scripts/enter.sh
+
+          # Target-specific firmware overlay
           if [ "${{matrix.target}}" == "panther_x2" ]; then
             echo 'source "$BR2_EXTERNAL_HASSOS_PATH/package/firmware_ap6236/Config.in"' >> buildroot-external/Config.in
           fi
@@ -97,12 +88,10 @@ jobs:
           if [ "${{matrix.target}}" == "ihost" ]; then
             echo 'source "$BR2_EXTERNAL_HASSOS_PATH/package/matter/Config.in"' >> buildroot-external/Config.in
             cp -r buildroot-external/board/sonoff/rootfs-overlay/* buildroot-external/rootfs-overlay/
-            cp -r buildroot-external/board/sonoff/0001-CMD-read-string-from-fileinto-env.patch buildroot-external/patches/uboot/0001-CMD-read-string-from-fileinto-env.patch
+            cp -r buildroot-external/board/sonoff/0001-CMD-read-string-from-fileinto-env.patch buildroot-external/patches/uboot/
           fi
-          
-          
-          sed -i 's|Etc/UTC|Asia/Shanghai|g' buildroot/system/Config.in
 
+          sed -i 's|Etc/UTC|Asia/Shanghai|g' buildroot/system/Config.in
           echo "BR2_PACKAGE_UNZIP=y" >> buildroot-external/configs/${{matrix.target}}_defconfig 
           echo "BR2_TARGET_LOCALTIME=\"Asia/Shanghai\"" >> buildroot-external/configs/${{matrix.target}}_defconfig
           echo -e "${{ secrets.RAUC_CERTIFICATE }}" > cert.pem
@@ -110,14 +99,31 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-    
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build 
+      - name: Pull required ha-china images
+        run: |
+          images=("haos-supervisor:latest" "homeassistant:latest")
+          for img in "${images[@]}"; do
+            count=0
+            max_retries=3
+            until docker pull ghcr.nju.edu.cn/ha-china/$img; do
+              count=$((count + 1))
+              if [ $count -ge $max_retries ]; then
+                echo "Failed to pull $img after $count attempts"
+                exit 1
+              fi
+              echo "Retry pulling $img in 10s... ($count/$max_retries)"
+              sleep 10
+            done
+          done
+
+      - name: Build
         shell: 'script -q -e -c "bash {0}"'
         id: build
         run: |
@@ -125,8 +131,8 @@ jobs:
           cd operating-system
           max_retries=3
           count=0
-          until scripts/enter.sh make -j$(($(nproc) + 1)) ${{matrix.target}}; do
-            count=$((count + 1))
+          until scripts/enter.sh make -j$(($(nproc)+1)) ${{matrix.target}}; do
+            count=$((count+1))
             if [ $count -ge $max_retries ]; then
               echo "Build failed after $count attempts."
               exit 1
@@ -134,15 +140,12 @@ jobs:
             echo "Build failed. Retrying in 30s... (Attempt $count/$max_retries)"
             sleep 30
           done
-          
+
       - name: Get current date
         id: current_date
         run: |
           current_date=$(date +'%Y-%m-%d')
           echo "CURRENT_DATE=${current_date}" >> $GITHUB_ENV
-      
-      - name: Use current date
-        run: echo "Current date is $CURRENT_DATE"
 
       - name: Upload images to release
         id: upload-release
@@ -153,4 +156,4 @@ jobs:
           tag: ${{ env.HASSOS_VERSION }}
           overwrite: true
           file_glob: true
-          body: "Home Assistant 国内版镜像，是专为中国大陆用户优化的 Home Assistant 系统镜像。通过替换了版本检测源、Supervisor 镜像源、联网检测源、NTP 服务，预设为中国时区，优化了国内使用环境。解决了官方镜像在国内下载速度慢、部分依赖无法安装的问题。用户可直接使用该镜像安装或升级 Home Assistant，实现开箱即用、快速稳定。"
+          body: "接近原版的Home Assistant OS，全部以正常访问为前提，做最小的优化原版."
